spring.application.name=shop



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
#jdbc:postgresql://172.19.0.2:5432/cimmino
spring.datasource.username=${DB_USER}
#myuser
spring.datasource.password=${DB_PASSWORD}
#mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false



server.address=0.0.0.0
#server.port=${PORT}
management.server.port=10000

server.forward-headers-strategy=framework



spring.boot.admin.client.url=https://adminserver-qfva.onrender.com
#spring.boot.admin.client.url=http://localhost:9090

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

management.info.env.enabled=true
logging.level.root=INFO

logging.level.com.boymask=DEBUG


management.endpoint.loggers.enabled=true
management.endpoint.logfile.enabled=true
logging.file.path=logs
logging.file.name=logs/app.log